list1 = ["Słuchajcie Państwo:", "Trzeba to powiedzieć:", "Powiedzmy wyraźnie:", "Nikt nie może zaprzeczyć:", "Ja tylko Państwu przypomnę -", "Powiem to wyraźnie:", "Ktoś to musi powiedzieć -", "Jak zwylke prawda wychodzi na jaw, bo", "Powtórzę raz jeszcze:", "Trzeba powiedzieć jasno:", "Ja chciałem Państwu przypomnieć:", "Zauważcie Państwo:", "Ja jestem liberałem – i uważam, że", "Macie Państwo rację:", "Nikogo nie będę przepraszać:", "Takie są skutki powszechnej oświaty."]

list2 = ["te bezczelne lewaki", "agenci bezpieki", "tak zwani ekolodzy", "feminazistki", "ci chorzy geje", "ekonaziści", "babilońskie nierządnice", "niemieckie prostytutki z syfilisem", "europejskie gumisie", "neonazistowskie niemowlaki z alzheimerem", "ci komunistyczni idioci", "funkcjonariusze reżymowej telewizji", "komunistyczni krwiopijcy", "bezsilni opozycjoniści", "te jebane lewaki", "ci prounijni skurwiele", "te tak zwane feministki", "szalejący biurokraci Unii Europejskiej", "świnie przy korycie", "hordy tchórzy i donosicieli", "małpy zwane socjalistami", "Czerwoni w parlamencie", "bandyci z UOP", "unijni urzędnicy", "homosie", "niewolnicy euro-socjalizmu", "wściekłe lewaki", "skurwione skurwiele", "zboczeńcy, mordercy i słabeusze"]

list3 = ["zupełnie bezkarnie", "kompletnie bezczelnie", "absolutnie niedorzecznie", "śpiewając \"boże coś polskę\"", "maczając języki w krwi niewinnych", "krusząc mury rozsądku", "z pełną premedytacją", "bez mrugnięcia okiem", "celowo i świadomie", "bez zastanowienia", "zakładając komunistyczną jarmułkę", "plując nam w twarz", "śmiejąc nam się w twarz", "kłamiąc w żywe oczy", "ślepo wykonując rozkazy", "nie przestrzegając zasad moralnych", "robiąc co chcą"]

list4 = ["nawołują do podniesienia podatków", "atakują naszą wolność", "kłamią w żywe oczy", "masturbują wyobraźnię mas", "kopulują na grobie demokracji", "srają na polskie dziedzictwo", "zakazują posiadania broni", "nie dopuszczają prawicy do władzy", "niszczą polskie tradycje", "atakują wolny rynek", "otumaniają społeczeństwo polskie faszystowską propagandą", "są w stanie jeść bez soli byle inni też mieli źle", "sieją analfabetyzm", "szczepionkami zaburzają równowagę środowiska naturalnego", "mącą poglądy wyborców", "niszczą różnorodność", "zakazują zażywania heroiny"]

list5 = ["bo głupich jest więcej niż mądrych", "bo myślą że tworzą raj na ziemi", "bo chcą niszczyć cywilizację białego czlowieka", "bo bez tego demokracja (tfu!) nie może istnieć", "skupując katolickie kamienice", "budując niewolniczy euro-socjalizm", "bo chcą zademonstrować swoją wyższość nad bliźnimi", "bo myślą że w ten sposób rozwalą patriarchat", "bo zrobią wszystko żeby utrzymać się przy korycie", "byleby tylko sprowokować skandal", "bo działają dla zasady \"róbta co chceta\""]

list6 = ["i dlatego Polska umiera.", "- proszę zobaczyć, to się dzieje na Zahodzie, jeśli mi Państwo nie wierzą", "i dlatego bóg nas opuścił", "i dlatego nie ma budulca dla wiary", "- kto nie widział niech nie pierdoli", "- tak samo było za Hitlera", "niszcząc nas stalinizmem", "- dlatego Związek Sowiecki już dogania USA", "- każdy kij ma dwa końce", "i dlatego należy ich wysłać do obozu reedukacji i tyle", "i dlatego należy im jasno powiedzieć - żadnych eksperymentów", "i dlatego uważam, że za mało budujemy w Polsce szubienic", "- to nie ja mam się podlizywać wyborcom, to oni muszą mieć na mnie ochotę", "- tylko bankructwo całego tego systemu może spowodować, że ludzie zaczną naprawdę liczyć", "i dlatego góral nie może sobie robić oscypków takich jakby chciał", "i dlatego należy im odebrać prawa wyborcze", "- tak bym to podsumował"]